rex/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
	path('rex/', include('rex_app.urls')),
    path('breakingdoors/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),

]

rex_app/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('create_user', views.create_user, name='create_user'),
    path('home', views.home_detail, name='home'),
    path('question/create', views.create_question, name='create_question'),
    path('tag/create', views.create_tag, name='create_tag'),
    path('answer/create/<int:question_pk>', views.create_answer, name='create_answer'),
    path('answer/edit/<int:answer_pk>', views.edit_answer, name='edit_answer'),
    path('comment/create/<int:answer_pk>', views.create_comment, name='create_comment'),
    path('question/<int:pk>', views.question_detail, name='question_detail'),
    path('question/edit/<int:pk>', views.EditQuestion.as_view(), name='edit_question'),
    path('search', views.search, name='search'),
    path('search_for_user', views.search_for_user, name='search_for_user'),
    path('upvote/<int:answer_pk>', views.upvote, name='upvote'),
    path('downvote/<int:answer_pk>', views.downvote, name='downvote'),
    path('accept/<int:answer_pk>', views.mark_accepted, name='accept'),
    path('settings/<int:pk>', views.EditUserAttributes.as_view(), name='settings'),
    path('friends/list', views.friends_list, name='friends_list'),
    path('friends/add/<int:pk>', views.add_friend, name='add_friend'),
    path('friends/remove/<int:pk>', views.remove_friend, name='remove_friend'),
    path('friends/accept/<int:pk>', views.accept_friend, name='accept_friend'),
    path('friends/reject/<int:pk>', views.reject_friend, name='reject_friend'),
    path('dm/inbox', views.inbox, name='inbox'),
    path('dm/create', views.DirectMessageCreate.as_view(), name='direct_message_create'),
    path('dm/conversation/<int:other_user_pk>', views.show_conversation, name='show_conversation'),
    path('profile/<int:pk>', views.Profile.as_view(), name='profile'),
    path('achievements/<int:pk>', views.Achievements.as_view(), name='achievements'),
    


    
    
]

rex_app/models.py
from django.db import models
from django.contrib.auth.models import User

class GlobalPermissions(models.Model):
    class Meta:
        managed = False
        default_permissions = ()
        permissions = (
            ('moderator', 'Can moderate'),
            ('voter', 'Can upvote/downvote'),
        )

class Colors(models.IntegerChoices):
    DARK = 1, '#212529'
    BLUE = 2, '#001442'
    GREEN = 3, '#00321b'

class Avatars(models.TextChoices):
    PX = 1, 'fab fa-500px'
    ANGRY = 2, 'far fa-angry'
    backspace = 3, 'fas fa-backspace'
    atom = 4, 'fas fa-atom'
    battle_net = 5, 'fab fa-battle-net'
    biohazard = 6, 'fas fa-biohazard'
    braille = 7, 'fas fa-braille'
    burn = 8, 'fas fa-burn'
    mapleleaf = 9, 'fab fa-canadian-maple-leaf'
    carcrash = 10, 'fas fa-car-crash'


class DirectMessage(models.Model):
    from_user = models.ForeignKey(User, on_delete=models.PROTECT, related_name='from_user_reverse')
    to_user = models.ForeignKey(User, on_delete=models.PROTECT, related_name='to_user_reverse')
    time_stamp = models.DateTimeField(auto_now_add=True)
    text = models.CharField(max_length=99999)

    def __str__(self):
    	return str(self.from_user)+'>'+str(self.to_user)+' '+self.text


class UserAttribute(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    background_color = models.IntegerField(choices=Colors.choices, default=Colors.DARK)    
    avatar = models.CharField(max_length=99999, choices=Avatars.choices, default=Avatars.PX)
    birthday=models.DateField(null=True, blank=True)
    reputation = models.IntegerField(default=0)
    friends = models.ManyToManyField(
        User,
        through='FriendAdditionalDetail', 
        through_fields=('user_attribute', 'user'),
        related_name='friends_reverse',
        )
    def is_upvote_allowed(self):                        
        return True if self.reputation > 20 else False

    def add_rep_for_question(self):
        self.reputation += 10
        self.save()
    


    def is_shop_unlocked(self):
        return True if self.reputation > 50 else False  
              
    def get_avatar_list(self):
        return [(Avatars.PX, 'PX avatar','fab fa-500px', True ),
                (Avatars.ANGRY, 'Angry avatar', 'far fa-angry', self.reputation > 25),
                (Avatars.atom, 'Atom avatar',  'fas fa-atom', self.reputation > 50)]

    def get_color_list(self):
        return [(Colors.BLUE, 'Blue', '#001442', True), 
                (Colors.DARK, 'Dark', '#212529', self.reputation > 25),
                (Colors.GREEN, 'Green', '#00321b', self.reputation > 50),]
    

class FriendStatus(models.IntegerChoices):
    AWAITING_APPROVAL = 1, 'AWAITING_APPROVAL'
    REJECTED = 2, 'REJECTED'
    APPROVED = 3, 'APPROVED'

class FriendAdditionalDetail(models.Model):
    class Meta:
        unique_together = ('user_attribute', 'user')
    user_attribute = models.ForeignKey(UserAttribute, on_delete=models.PROTECT)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    status = models.IntegerField(choices=FriendStatus.choices)    

    def save(self, *args, **kwargs):
        if self.user_attribute.user == self.user:
            raise ValidationError('Can\'t become friends with yourself.')
        super().save(*args, **kwargs)

class Tag(models.Model):
    text = models.CharField(max_length=20, unique=True)
    
    def __str__(self):
        return self.text[:200]

class Question(models.Model):
    title = models.CharField(max_length=99)
    text = models.CharField(max_length=99999)
    asked_by = models.ForeignKey(User, on_delete=models.PROTECT)
    date = models.DateTimeField(auto_now_add=True)
    tag = models.ManyToManyField(Tag)

    def __str__(self):
        return self.text[:200]

class Answer(models.Model):
    text = models.CharField(max_length=99999)
    upvotes = models.IntegerField(default=0)
    accepted = models.BooleanField(default=False)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answered_by = models.ForeignKey(User, on_delete=models.PROTECT)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text[:200] + str(self.upvotes) + str(self.accepted)

class Comment(models.Model):
    text = models.CharField(max_length=99999)
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
    commented_by = models.ForeignKey(User, on_delete=models.PROTECT)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text[:200]

rex_app/views.py
from django.shortcuts import render, redirect
from django import forms
from django.http import HttpResponse
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import get_object_or_404, reverse
from django.contrib import messages
from random import randint
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin,PermissionRequiredMixin
from django.contrib.auth.models import User
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic.edit import FormMixin
from django.views.generic.list import MultipleObjectMixin
from .models import *
from django.views.generic import ListView, CreateView, UpdateView, DetailView
from django.db import IntegrityError
from django.db.models import Q
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Fieldset, ButtonHolder


########################################################################
# Creating users
########################################################################

def create_user(request):
    form = UserCreationForm()

    if request.method == 'POST':

        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save() 
            UserAttribute.objects.create(user=user)
            return redirect('home')

    return render(request,'rex_app/create_user.html', {
            "form": form,    
        }) 


########################################################################
# Direct messages
########################################################################

@login_required
def show_conversation(request, other_user_pk):
    other_user = get_object_or_404(User, pk=other_user_pk)
    dms = DirectMessage.objects.filter(
        (Q(from_user=request.user) & Q(to_user=other_user))
    |   (Q(to_user=request.user) & Q(from_user=other_user) ))
    return render(request, 'rex_app/show_conversation.html', {
        'dms': dms,
        })

@login_required
def inbox(request):
    dms = DirectMessage.objects.filter(Q(from_user=request.user) | Q(to_user=request.user))
    user_set = set()
    for dm in dms:
        if request.user == dm.from_user:
            user_set.add(dm.to_user)
        else:
            user_set.add(dm.from_user)
    return render(request, 'rex_app/inbox.html', {
        'user_set': user_set,
        })

class DirectMessageForm(forms.ModelForm): 
    class Meta:
        model = DirectMessage
        fields = ['to_user', 'text']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs) 
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_action = reverse('direct_message_create')
        self.helper.add_input(Submit('submit', 'Submit', css_class='btn-warning')) 


class DirectMessageCreate(LoginRequiredMixin, CreateView):
    model = DirectMessage
    form_class = DirectMessageForm

    def form_valid(self, form):
        form.instance.from_user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('inbox')

########################################################################
# Homepage
########################################################################

@login_required
def home_detail(request):
    top_three_recent = Question.objects.all().order_by('-date')[:3]
    current_user = UserAttribute.objects.get(user=request.user)

    return render(request,'rex_app/home.html', {
        'recents': top_three_recent,
        'questions': Question.objects.all(),     
        }) 

########################################################################
# Questions
########################################################################

@login_required
def question_detail(request, pk):

    question = get_object_or_404(Question, pk=pk)

    return render(request, 'rex_app/question_detail.html', {
        'question': question,
        'questions': Question.objects.all(),
        'answers': Answer.objects.all(),

        }) 

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['title', 'text', 'tag']
        widgets = {
            'text': forms.Textarea(attrs={'cols':200, 'rows': 20}),
        }

@login_required
def create_question(request):

    form = QuestionForm()

    if request.method == 'POST':

        form = QuestionForm(request.POST)

        if form.is_valid():
            request.user.userattribute.add_rep_for_question()
            question = form.save(commit=False)
            question.asked_by = request.user
            question.save()
            form.save_m2m()

            messages.add_message(request, messages.SUCCESS, 'Question successfully created!')
            return redirect('question_detail', pk=question.pk)

        else:
            messages.add_message(request, messages.ERROR, 'Terrible form D; ')

    return render(request, 'rex_app/create_question.html', {    
        'form': form,
    }) 

class EditQuestion(UserPassesTestMixin, UpdateView):
    model = Question
    form_class = QuestionForm

    def test_func(self):
        if not self.request.user.is_authenticated:
            return False
        return self.request.user == self.get_object().asked_by 

    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS, 'Question successfully edited!')
        return reverse('question_detail', kwargs={'pk':self.get_object().pk}) 

########################################################################
# Answer
########################################################################

@login_required
def create_answer(request, question_pk):
    form = AnswerForm()
    if request.method == 'POST':

        form = AnswerForm(request.POST)

        if form.is_valid():
            request.user.userattribute.add_rep_for_question()
            answer = form.save(commit=False)
            answer.question = Question.objects.get(pk=question_pk)
            answer.answered_by = request.user
            answer.save()

            messages.add_message(request, messages.SUCCESS, 'Answer successfully created!')
            return redirect('question_detail', pk=question_pk)

        else:
            messages.add_message(request, messages.ERROR, 'Terrible form D; ')

    return render(request, 'rex_app/create_answer.html', {
        'form': form,
        'question_pk': question_pk,
    }) 

@login_required
def edit_answer(request, answer_pk):

    answer = get_object_or_404(Answer, pk=answer_pk)
    form = AnswerForm(instance=answer)     

    if request.method == 'POST':

        form = AnswerForm(request.POST,instance=answer)

        if form.is_valid() and request.user == answer.answered_by:
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Answer successfully edited!')
            return redirect('question_detail', pk=answer.question.pk)

        else:
            messages.add_message(request, messages.ERROR, 'dont you dare change someone elses answer')
           
    return render(request, 'rex_app/edit_answer.html', {
        'form': form,
        'answer_pk': answer_pk,       
    })        

########################################################################
# Comment
########################################################################

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

@login_required
def create_comment(request, answer_pk):

    answer = get_object_or_404(Answer, pk=answer_pk)
    form = CommentForm()

    if request.method == 'POST':

        form = CommentForm(request.POST)
        if form.is_valid():
            
            request.user.userattribute.add_rep_for_question()
            comment = form.save(commit=False)
            comment.answer = answer
            comment.commented_by = request.user
            comment.save()
            messages.add_message(request, messages.SUCCESS, 'Comment successfully created!')            

            return redirect('question_detail', pk=comment.answer.question.pk)

        else:
            messages.add_message(request, messages.ERROR, 'Terrible form D; ')

    return render(request, 'rex_app/create_comment.html', {
        'form': form,
        'answer_pk': answer_pk,
    }) 

########################################################################
# Tags
########################################################################

class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ['text']

@login_required
def create_tag(request):

    form = TagForm()

    if request.method == 'POST':

        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Tag successfully created!')
            return redirect('create_question')
            
        else:
            messages.add_message(request, messages.ERROR, 'Terrible form D; ')

    return render(request, 'rex_app/create_tag.html', {    
        'form': form,
    }) 

########################################################################
# UserAttributes
########################################################################

class UserAttributeForm(forms.ModelForm):
    class Meta:
        model = UserAttribute
        fields = ['background_color', 'avatar', 'birthday' ]

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs) 
        self.fields['background_color'].choices = [(color[0], color[2]) for color in user.userattribute.get_color_list() if color[3]]
        self.fields['avatar'].choices = [(avatar[0], avatar[2]) for avatar in user.userattribute.get_avatar_list() if avatar[3]]

rex_app/templates/rex_app/achievements.html
{% extends 'rex_app/base.html' %}

{% block content %}


<div class="card">
  <div class="card-header text-center">
    <h2 class="text-center">Achievements</h2>
  </div>

<div class="row">
  {% for avatar, name, css, is_unlocked in user.userattribute.get_avatar_list %}
  <div class="col-sm-4">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">{{name}}</h5>
        <p class="card-text"><i class="{{css}}"></i></p>
        {% if is_unlocked %}
          <a href="#" class="btn btn-primary">Unlocked</a>
        {% else %}
          <a href="#" class="btn btn-warning">Locked</a>
        {% endif %}      
      </div>
    </div>
  </div>
  {% endfor %}
 
{% endblock %}


	

rex_app/templates/rex_app/change_color.html
{% extends 'rex_app/base.html' %}

{% block content %}


<div class="card">
  <div class="card-header text-center">
    <h2 class="text-center">Change Color</h2>
  </div>
  <div class="card-body">
  	<form method="post" action="{% url 'change_color' user.pk %}">
		{% csrf_token %}
		{{form.as_p}}
		<input type="submit" name="submit_mode" value="OK">
	</form>
  </div>
</div>
{% endblock %}

rex_app/templates/rex_app/create_user.html
{% extends 'rex_app/base.html' %}

{% block content %}


<div class="card">
  <div class="card-body">
  	<form method="post" action="{% url 'create_user' %}">
        {{form.as_p}}
        {% csrf_token %}
        <input class="btn btn-outline-success btn-sm" type="submit" name="submit_mode" value="Create Account">
    </form>

  </div>
</div>
{% endblock %}

rex_app/templates/rex_app/directmessage_form.html
{% extends 'rex_app/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<div class="row">
	<div class="col-sm-8 mx-auto">
		<div class="card">
			<div class="card-header text-center">
				<h2 class="text-center">Send message</h2>
			
				<a href="{% url 'inbox' %}" class="btn btn-outline-info">Inbox</a>	
				{% crispy form %}
			</div>
		</div>
	</div>
</div>



{% endblock content %}
				

rex_app/templates/rex_app/directmessage_list.html
{% extends 'rex_app/base.html' %}

{% block content %}
{% load inbox_tags %}

<div class="card">
	<div class="card-header text-center">
		<h2 class="text-center">Users</h2>
	{% comment %} </div>
		<a href="{% url 'direct_message_list' %}" class="btn btn-outline-info">Inbox</a>	
	</div> {% endcomment %}

</div>
{% show_dms object_list request.user %}


{% endblock content %}

rex_app/templates/rex_app/edit_answer.html
{% extends 'rex_app/base.html' %}

{% block content %}


<div class="card">
  <div class="card-header text-center">
    <h2 class="text-center">Edit Answer</h2>
  </div>
  <div class="card-body">
	<form method="post" action="{% url 'edit_answer' answer_pk %}">
		{% csrf_token %}
		{{form.as_p}}
		<input type="submit" name="submit_mode" value="OK">
	</form>

  </div>
</div>

{% endblock %}

rex_app/templates/rex_app/friends_list.html
{% extends 'rex_app/base.html' %}



{% block content %}

<div class="card">
	<div class="card-header text-center">
		<h2 class="text-center">Friends</h2>
	</div>
	<div class="card-body">
		<form class="form-inline my-2 my-lg-0" action="{% url 'search_for_user' %}">
			<input class="form-control mr-sm-2" type="text" id="searchbox" placeholder="Search for user" name="searchbox">
			<input class="btn btn-outline-info" type="submit" value="Submit">
		</form>  
	</div>
	<div class="card-body">
		<h2>Current Friends</h2>

		{% for friend in friends%}
			<div class="container ml-1">
				<div class="row justify-content-start no-gutters">
					<div class="col-2">
						<a href="{% url 'profile' friend.user.pk %}">{{friend.user.username}}</a>
					</div>

				</div>
			</div>	
		{% endfor %}

	</div>

	
	<div class="card-body">
		<h2>Incoming friend requests</h2>
		{% for friend in friends_incoming_waiting_approval%}
			
			<div class="container ml-1">
				<div class="row justify-content-start no-gutters">
					<div class="col-2">
						<a href="{% url 'profile' user.pk %}">{{friend.user.username}}</a>
					</div>

					<div class="col-1">
						<form method="post" action="{% url 'accept_friend' friend.pk %}">
							{% csrf_token %}
							<input class="btn btn-outline-success btn-sm" type="submit" name="submit_mode" value="Accept">
						</form>		
					</div>
		
					<div class="col-1 ">
						<form method="post" action="{% url 'reject_friend' friend.pk %}">
							{% csrf_token %}
							<input class="btn btn-outline-danger btn-sm" type="submit" name="submit_mode" value="Reject">
						</form>
					</div>
				</div>
			</div>		
		{% endfor %}
	</div>
</div>

<div class="card-body">
	<h2>Outgoing friend requests</h2>
	{% for friend in friends_outgoing_waiting_approval %}
		
		<div class="container ml-1">
			<div class="row justify-content-start no-gutters">
				<div class="col-2">
					<a href="{% url 'profile' user.pk %}">{{friend.user.username}}</a>
				</div>

				<div class="col-1 ">
					<form method="post" action="{% url 'reject_friend' friend.pk %}">
						{% csrf_token %}
						<input class="btn btn-outline-danger btn-sm" type="submit" name="submit_mode" value="Reject Request">
					</form>
				</div>
			</div>
		</div>		
	{% endfor %}
</div>

{% endblock content %}

rex_app/templates/rex_app/inbox.html
{% extends 'rex_app/base.html' %}

{% block content %}
{% load inbox_tags %}

<div class="card">
	<div class="card-header text-center">
		<h2 class="text-center">Users</h2>

</div>
<p>{{DirectMessage.from_user}}</p>
{% for user in user_set %}
	<a class="btn btn-outline-success btn-sm my-2 " href="{% url 'show_conversation' user.pk %}">{{user.username}}</a>
{% endfor %}
{% endblock content %}

rex_app/templates/rex_app/profile.html
{% extends 'rex_app/base.html' %}
{% load humanize %}


{% block content %}

<div class="card">
	<div class="card-header text-center">
		<h2 class="text-center">Profile</h2>
	</div>

	<div class="card-body">

		<h3>User: {{object.user}}</h3>
		<h3>Birthday: {{object.birthday}}</h3>
		<h3>Avatar: <i class="{{object.get_avatar_display}}"></i></h3>
		<h3>Reputation: {{object.reputation}}</h3>
		<h3>Asked Questions: </h3>
		{% for question in object.user.question_set.all %}
			<p><a href="{% url 'question_detail' question.pk %}" class="btn btn-outline-info btn-sm">{{question}}  </a> <b>  	 Asked: </b> {{question.date|naturaltime}}</p>
		{% endfor %} 
	</div>
	
	{% if object.user != request.user %}
		<form method="post" action="{% url 'add_friend' object.user.pk %}">
			{% csrf_token %}
			<input class="btn btn-outline-success btn-sm" type="submit" name="submit_mode" value="Add">
		</form>
	
		<form method="post" action="{% url 'remove_friend' object.user.pk %}">
			{% csrf_token %}
			<input class="btn btn-outline-danger btn-sm" type="submit" name="submit_mode" value="Remove">
		</form>

	{% endif %}

</div>`


{% endblock content %}

rex_app/templates/rex_app/question_form.html
{% extends 'rex_app/base.html' %}

{% block content %}


<div class="card">
  <div class="card-header text-center">
    <h2 class="text-center">Edit Question</h2>
  </div>
  <div class="card-body">
	<form method="post" action="{% url 'edit_question' question.pk %}">
		{% csrf_token %}
		{{form.as_p}}
		<input type="submit" name="submit_mode" value="Submit">
	</form>

  </div>
</div>

{% endblock %}

rex_app/templates/rex_app/search.html
{% extends 'rex_app/base.html' %}

{% block content %}


<div class="card">
  <div class="card-header bg-light">
    <h2 class="text-center">Results</h2>
  </div>
  <div class="card-body">
		<p class="card-text text-center">
			{% if not search_results_for_question and not search_results_for_answer and not search_results_for_tag %}
				NO RESULTS
			{% endif %}
		</p>

		<p class="card-text">
			<h4 class="text-center">Search by question:</h4><br>
			{% for question in search_results_for_question %}
				<a href="{% url 'question_detail' question.pk %}">{{question.title}}</a><br>
			{% endfor %}

		</p>

		<p class="card-text">
			<h4 class="text-center">Search by answer:</h4><br>
			{% for answer in search_results_for_answer %}
				<a href="{% url 'question_detail' answer.question.pk %}">{{answer.text}}</a><br>
			{% endfor %}
		</p>
		<p class="card-text">
			<h4 class="text-center">Search by tags:</h4><br>
			{% for tag in search_results_for_tag %}
				{% for question in tag.question_set.all %}
					<a href="{% url 'question_detail' question.pk %}">{{question}}</a><br>
				{% endfor %}
			{% endfor %}
		</p>
  </div>
</div>





{% endblock content %}

rex_app/templates/rex_app/search_for_user.html
{% extends 'rex_app/base.html' %}

{% block content %}

    <div class="card">
        <div class="card-header bg-light">
        <h2 class="text-center">Results</h2>
        </div>
        <div class="card-body">
            <p class="card-text text-center">
                {% if not search_results_for_username %}
                    NO RESULTS
                {% endif %}
            </p>
    
            <p class="card-text">
                <h4 class="text-center">Users:</h4><br>
                {% for user in search_results_for_username %}
                    <a href="{% url 'profile' user.pk %}">{{user.username}}</a><br>
                {% endfor %}
    
            </p>

{% endblock %}

rex_app/templates/rex_app/settings.html
{% extends 'rex_app/base.html' %}

{% block content %}

<div class="card">
  <div class="card-header text-center">
    <h2 class="text-center">Settings</h2>
  </div>
  <div class="card-body">
  	<p>{{user.userattribute.background_color}}</p>
  	<a href="{% url 'change_color' user.pk %}" class="btn btn-outline-info">Change Color</a></h4>
  </div>
</div>


{% endblock content %}

rex_app/templates/rex_app/userattribute_list.html
{% extends 'rex_app/base.html' %}



{% block content %}

<div class="card">
	<div class="card-header text-center">
		<h2 class="text-center">Profile</h2>
	</div>

	<div class="card-body">
		<h3>User: {{user.userattribute.user}}</h3>
		<h3>Color: {{user.userattribute.get_background_color_display}}</h3>
		<h3>{{avatar}}</h3>
		

		
		
	</div>
</div>


{% endblock content %}